/* This file was autogenerated by toolkit/crashreporter/generate_crash_reporter_sources.py. DO NOT EDIT */

package mozilla.components.lib.crash.service;

import androidx.annotation.AnyThread;

/**
 * Constants used by the crash reporter. These are generated so that they
 * are kept in sync with the other C++ and JS users.
 */
final class CrashReport {
    /** Crash Annotations */
    @AnyThread
    public enum Annotation {
        /** Message passed to NS_DebugBreak().
 */
AbortMessage("AbortMessage", "report"),
/** Set to "Active" by the accessibility service when it is active.
 */
Accessibility("Accessibility", "report"),
/** Accessibility client ID.
 */
AccessibilityClient("AccessibilityClient", "report"),
/** Hexadecimal mask of in-process accessibility consumers, see accessible/windows/msaa/Compatibility.h for the mappings.
 */
AccessibilityInProcClient("AccessibilityInProcClient", "report"),
/** Graphics adapter name.
 */
AdapterDeviceID("AdapterDeviceID", "report"),
/** Graphics adapter driver vendor.
 */
AdapterDriverVendor("AdapterDriverVendor", "report"),
/** Graphics adapter driver version.
 */
AdapterDriverVersion("AdapterDriverVersion", "report"),
/** Graphics adapter subsystem ID.
 */
AdapterSubsysID("AdapterSubsysID", "report"),
/** Graphics adapter vendor name.
 */
AdapterVendorID("AdapterVendorID", "report"),
/** Comma separated list of additional minidumps for this crash, each element in the list represent the suffix used in the dump filename. E.g. the "browser" entry for crash fa909194-737b-4b93-b8da-da110ac785e0 implies the existence of the fa909194-737b-4b93-b8da-da110ac785e0-browser.dmp file.
 */
additional_minidumps("additional_minidumps", "report"),
/** List of currently enabled add-ons.
 */
Addons("Addons", "report"),
/** The name of the underlying board used by the Android device. e.g. "k68v1_64"
 */
Android_Board("Android_Board", "report"),
/** The consumer-visible brand associated with this Android device. e.g. "vivo"
 */
Android_Brand("Android_Brand", "report"),
/** The Android primary CPU ABI being used. e.g. "arm64-v8a"
 */
Android_CPU_ABI("Android_CPU_ABI", "report"),
/** The Android secondary CPU ABI being used. e.g. "armeabi-v7a"
 */
Android_CPU_ABI2("Android_CPU_ABI2", "report"),
/** Android device name. e.g. "1907"
 */
Android_Device("Android_Device", "report"),
/** End-user visible display name of the build id for the Android build. e.g. "SP1A.210812.003 release-keys"
 */
Android_Display("Android_Display", "report"),
/** A string that uniquely identifies the Android build. e.g. "vivo/1907/1907:12/SP1A.210812.003/compiler03091510:user/release-keys"
 */
Android_Fingerprint("Android_Fingerprint", "report"),
/** The name of the Android hardware from "/proc". e.g. "mt6768"
 */
Android_Hardware("Android_Hardware", "report"),
/** Android device manufacturer. e.g. "vivo"
 */
Android_Manufacturer("Android_Manufacturer", "report"),
/** End-user visible Android device model name. e.g. "vivo 1907"
 */
Android_Model("Android_Model", "report"),
/** The package name of an Android application that uniquely identifies the application on the device, Google Play Store, and third-party Android stores. e.g. "com.example.referencebrowser"
 */
Android_PackageName("Android_PackageName", "report"),
/** The name of the process which sent the crash report in the Android application.
 */
Android_ProcessName("Android_ProcessName", "report"),
/** The developer preview revision of a prerelease SDK plus The current development codename, or the string "REL" if this is a release build. e.g. "31 (REL)"
 */
Android_Version("Android_Version", "report"),
/** The version of android-components in use.
 */
AndroidComponentVersion("AndroidComponentVersion", "report"),
/** List of DLLs loaded when launching any application on Windows, this reflects the contents of the AppInit_DLLs registry key.
 */
AppInitDLLs("AppInitDLLs", "report"),
/** Product application's build ID.
 */
ApplicationBuildID("ApplicationBuildID", "report"),
/** The version of Application Services libraries. */
ApplicationServicesVersion("ApplicationServicesVersion", "report"),
/** This annotation is present if a shutdown blocker was not released in time and the browser was crashed instead of waiting for shutdown to finish. The condition that caused the hang is contained in the annotation.
 */
AsyncShutdownTimeout("AsyncShutdownTimeout", "ping"),
/** Available commit-space in bytes. - Under Windows, computed from the PERFORMANCE_INFORMATION structure by substracting
  the CommitTotal field from the CommitLimit field.
- Under Linux, computed from /proc/meminfo's CommitLimit - Committed_AS. Note that
  the kernel is not guaranteed to enforce that CommittedLimit &gt;= Committed_AS. If
  Committed_AS &gt; CommittedLimit, this value is set to 0.
- Not available on other platforms.
 */
AvailablePageFile("AvailablePageFile", "ping"),
/** Amount of free physical memory in bytes. - Under Windows, populated with the contents of the MEMORYSTATUSEX's structure ullAvailPhys field. - Under macOS, populated with vm_statistics64_data_t::free_count. - Under Linux, populated with /proc/meminfo's MemFree. - Not available on other platforms.
 */
AvailablePhysicalMemory("AvailablePhysicalMemory", "ping"),
/** Amount of free swap space in bytes. - Under macOS, populated with the contents of
  sysctl "vm.swapusage" :: xsu_avail.
- Under Linux, populated with /proc/meminfo's SwapFree. - Not available on other platforms.
 */
AvailableSwapMemory("AvailableSwapMemory", "ping"),
/** Amount of free virtual memory in bytes - Under Windows, populated with the contents of the MEMORYSTATUSEX's structure ullAvailVirtual field. - Under Linux, populated with /proc/meminfo's MemAvailable. - Not available on other platforms. - For macOS, see AvailableSwapMemory, AvailablePhysicalMemory and PurgeablePhysicalMemory.
 */
AvailableVirtualMemory("AvailableVirtualMemory", "ping"),
/** True if the app was invoked in background task mode via `--backgroundtask ...`, false otherwise.
 */
BackgroundTaskMode("BackgroundTaskMode", "report"),
/** If the app was invoked in background task mode via `--backgroundtask &lt;task name&gt;`, the string "task name".
 */
BackgroundTaskName("BackgroundTaskName", "ping"),
/** Comma-separated list of blocked DLLS, Windows-only
 */
BlockedDllList("BlockedDllList", "ping"),
/** Set to 1 if the DLL blocklist could not be initialized.
 */
BlocklistInitFailed("BlocklistInitFailed", "ping"),
/** Trail of events that occurred before a report. this will consist of multiple breadcrumbs with timestamp, message, category, level, type and data in JSON format.
 */
Breadcrumbs("Breadcrumbs", "report"),
/** Application build ID, the format is YYYYMMDDHHMMSS.
 */
BuildID("BuildID", "ping"),
/** The user comments for a crash, recorded by the crash reporter client.
 */
Comments("Comments", "report"),
/** List of capabilities of the content process sandbox.
 */
ContentSandboxCapabilities("ContentSandboxCapabilities", "report"),
/** Set to 1 if the client is capable of content sandboxing.
 */
ContentSandboxCapable("ContentSandboxCapable", "report"),
/** Set to 1 when content process sandboxing is enabled.
 */
ContentSandboxEnabled("ContentSandboxEnabled", "report"),
/** Content sandbox level.
 */
ContentSandboxLevel("ContentSandboxLevel", "report"),
/** Content sandbox Win32k state
 */
ContentSandboxWin32kState("ContentSandboxWin32kState", "report"),
/** Version of the CPU microcode.
 */
CPUMicrocodeVersion("CPUMicrocodeVersion", "report"),
/** Crash time in seconds since the Epoch.
 */
CrashTime("CrashTime", "ping"),
/** The type of crash that occurred (Android-only). */
CrashType("CrashType", "report"),
/** Reason why the cycle collector crashed.
 */
CycleCollector("CycleCollector", "report"),
/** Desktop environment used on Linux, e.g. GNOME, KDE, XFCE, etc.
 */
DesktopEnvironment("DesktopEnvironment", "report"),
/** Reason why a DirectX device has been reset, Windows only.
 */
DeviceResetReason("DeviceResetReason", "report"),
/** The distribution ID of the application. */
DistributionID("DistributionID", "report"),
/** Set to 1 when DOM fission is enabled, and subframes are potentially loaded in a separate process.
 */
DOMFissionEnabled("DOMFissionEnabled", "ping"),
/** Set to 1 when a tab is running in a content process
 */
DOMIPCEnabled("DOMIPCEnabled", "report"),
/** Error message of the minidump writer, in case there was an error during dumping.
 */
DumperError("DumperError", "report"),
/** Set to true if add-on compatibility checking is enabled. Technically this annotation should be a boolean, but historically it's been set by JavaScript code as a string, so keep it as such for the time being.
 */
EMCheckCompatibility("EMCheckCompatibility", "report"),
/** Present only if higher than 0, indicates that we're running in a nested event loop and indicates the nesting level.
 */
EventLoopNestingLevel("EventLoopNestingLevel", "ping"),
/** Set before attempting to load a font to help diagnose crashes during loading.
 */
FontName("FontName", "ping"),
/** The version of geckoview in use. */
GeckoViewVersion("GeckoViewVersion", "report"),
/** The version of Glean in use. */
GleanVersion("GleanVersion", "report"),
/** Holds the path to the GMP plugin library.
 */
GMPLibraryPath("GMPLibraryPath", "report"),
/** Set to 1 if the GMP plugin is enabled.
 */
GMPPlugin("GMPPlugin", "report"),
/** Number of times the GPU process was launched.
 */
GPUProcessLaunchCount("GPUProcessLaunchCount", "ping"),
/** Status of the GPU process, can be set to "Running" or "Destroyed"
 */
GPUProcessStatus("GPUProcessStatus", "report"),
/** GPU sandbox level.
 */
GpuSandboxLevel("GpuSandboxLevel", "report"),
/** Name of the shader we are in the process of compiling, if applicable. See file names in gfx/wr/webrender/res/* for the possible values.
 */
GraphicsCompileShader("GraphicsCompileShader", "report"),
/** Information of a critical error that occurred within the graphics code.
 */
GraphicsCriticalError("GraphicsCriticalError", "report"),
/** Name of the shader that is currently bound for a draw call, if applicable. See file names in gfx/wr/webrender/res/* for the possible values.
 */
GraphicsDrawShader("GraphicsDrawShader", "report"),
/** Number of webrender renderer instances that are not in a paused state.
 */
GraphicsNumActiveRenderers("GraphicsNumActiveRenderers", "report"),
/** Total number of webrender renderer instances.
 */
GraphicsNumRenderers("GraphicsNumRenderers", "report"),
/** Set to 1 by the graphics driver crash guard when it's activated.
 */
GraphicsStartupTest("GraphicsStartupTest", "report"),
/** Set if the crash was the result of a hang, with a value which describes the type of hang (e.g. "ui" or "shutdown").
 */
Hang("Hang", "ping"),
/** Set to 1 if the device had a touch-screen, this only applies to Firefox desktop as on mobile devices we assume a touch-screen is always present.
 */
HasDeviceTouchScreen("HasDeviceTouchScreen", "report"),
/** True if the app was invoked in headless mode via `--headless ...` or `--backgroundtask ...`, false otherwise.
 */
HeadlessMode("HeadlessMode", "ping"),
/** The time when Firefox was installed expressed as seconds since the Epoch
 */
InstallTime("InstallTime", "report"),
/** Set before a content process crashes because of an IPC channel error, holds a description of the error.
 */
ipc_channel_error("ipc_channel_error", "ping"),
/** errno value retrieved after failing to set the O_CLOEXEC flag on a pipe used for IPC.
 */
IpcCreatePipeCloExecErrno("IpcCreatePipeCloExecErrno", "report"),
/** errno value retrieved after a call to fcntl() on a pipe used for IPC failed.
 */
IpcCreatePipeFcntlErrno("IpcCreatePipeFcntlErrno", "report"),
/** errno value retrieved after a socketpair() call failed while creating an IPC transport object.
 */
IpcCreatePipeSocketPairErrno("IpcCreatePipeSocketPairErrno", "report"),
/** Describes a fatal error that occurred during IPC operation.
 */
IPCFatalErrorMsg("IPCFatalErrorMsg", "report"),
/** Name of the protocol used by IPC when a fatal error occurred.
 */
IPCFatalErrorProtocol("IPCFatalErrorProtocol", "report"),
/** Size of failed shmem allocations which led to data being sent inline in the IPC message that caused a crash because it was too large.
 */
IPCMessageLargeBufferShmemFailureSize("IPCMessageLargeBufferShmemFailureSize", "report"),
/** Name of the IPC message that caused a crash because it was too large.
 */
IPCMessageName("IPCMessageName", "report"),
/** Size of the IPC message that caused a crash because it was too large.
 */
IPCMessageSize("IPCMessageSize", "report"),
/** Reason why reading an object via IPC failed.
 */
IPCReadErrorReason("IPCReadErrorReason", "report"),
/** IPC shutdown state, can be set to either "RecvShutdown" or "SendFinishShutdown" by a content process while it's shutting down.
 */
IPCShutdownState("IPCShutdownState", "report"),
/** Description of the last system error that occurred during IPC operation.
 */
IPCSystemError("IPCSystemError", "report"),
/** If true then the JavaScript garbage collector was running when the crash occurred.
 */
IsGarbageCollecting("IsGarbageCollecting", "ping"),
/** If true then the Wayland windowing system was in use.
 */
IsWayland("IsWayland", "report"),
/** If true then the WebRender resources (i.e. shaders) are loaded from a user specified path.
 */
IsWebRenderResourcePathOverridden("IsWebRenderResourcePathOverridden", "report"),
/** JSON structured Java stack trace, only present on Firefox for Android if we encounter an uncaught Java exception.
 */
JavaException("JavaException", "report"),
/** Java stack trace, only present on Firefox for Android if we encounter an uncaught Java exception.
 */
JavaStackTrace("JavaStackTrace", "report"),
/** If an actor is currently treating a message, this is the name of the message. Otherwise, empty.
 */
JSActorMessage("JSActorMessage", "report"),
/** If an actor is currently treating a message, this is the name of the actor. Otherwise, empty.
 */
JSActorName("JSActorName", "report"),
/** A large allocation couldn't be satisfied, check the JSOutOfMemory description for the possible values of this annotation.
 */
JSLargeAllocationFailure("JSLargeAllocationFailure", "ping"),
/** The error raised when attempting to import a critical JS module from C++
 */
JSModuleLoadError("JSModuleLoadError", "report"),
/** A small allocation couldn't be satisfied, the annotation may contain the "Reporting", "Reported" or "Recovered" value. The first one means that we crashed while responding to the OOM condition (possibly while running a memory-pressure observers), the second that we crashed after having tried to free some memory, and the last that the GC had managed to free enough memory to satisfy the allocation.
 */
JSOutOfMemory("JSOutOfMemory", "ping"),
/** How long the user had been inactive in seconds if the user was inactive at crash.  The value is not set if the user state was active.
 */
LastInteractionDuration("LastInteractionDuration", "ping"),
/** True if the last startup was detected to have been a crash.
 */
LastStartupWasCrash("LastStartupWasCrash", "report"),
/** Launcher process enabled state. The integer value of this annotation must match with one of the values in the mozilla::LauncherRegistryInfo::EnableState enum
 */
LauncherProcessState("LauncherProcessState", "report"),
/** Set to true if the memory pressure watcher was under memory pressure when the crash occurred.
 */
LinuxUnderMemoryPressure("LinuxUnderMemoryPressure", "report"),
/** Number of times the available memory tracker has detected that free physical memory is running low. This is a Windows-specific annotation.
 */
LowPhysicalMemoryEvents("LowPhysicalMemoryEvents", "ping"),
/** The value of the available memory sysctl 'kern.memorystatus_level'. Expected to be a percentage integer value.
 */
MacAvailableMemorySysctl("MacAvailableMemorySysctl", "report"),
/** The current memory pressure state as provided by the macOS memory pressure dispatch source. The annotation value is one of "Normal" for no memory pressure, "Unset" indicating a memory pressure event has not been received, "Warning" or "Critical" mapping to the system memory pressure levels, or "Unexpected" for an unexpected level. This is a Mac-specific annotation.
 */
MacMemoryPressure("MacMemoryPressure", "report"),
/** The time when the memory pressure state last transitioned to 'Critical' expressed as seconds since the Epoch.
 */
MacMemoryPressureCriticalTime("MacMemoryPressureCriticalTime", "report"),
/** The time when the memory pressure state last transitioned to 'Normal' expressed as seconds since the Epoch.
 */
MacMemoryPressureNormalTime("MacMemoryPressureNormalTime", "report"),
/** The value of the memory pressure sysctl 'kern.memorystatus_vm_pressure_level'. Indicates which memory pressure level the system is in at the time of the crash. The expected values are one of 4 (Critical), 2 (Warning), or 1 (Normal).
 */
MacMemoryPressureSysctl("MacMemoryPressureSysctl", "report"),
/** The time when the memory pressure state last transitioned to 'Warning' expressed as seconds since the Epoch.
 */
MacMemoryPressureWarningTime("MacMemoryPressureWarningTime", "report"),
/** Name of the currently executing nsIRunnable on the main thread.
 */
MainThreadRunnableName("MainThreadRunnableName", "ping"),
/** Set to 1 when Marionette (WebDriver Classic) is enabled.
 */
Marionette("Marionette", "report"),
/** The output of memory tests done by the crash reporter client after a crash in a JSON format
 */
MemtestOutput("MemtestOutput", "report"),
/** A string holding a JSON object describing which entity signed the modules present in the system. The format of this object is: { "Vendor1": [ "Module1", "Module2", ...], "Vendor2": [ "Module3", ... ] }
 */
ModuleSignatureInfo("ModuleSignatureInfo", "report"),
/** Plaintext description of why Firefox crashed, this is usually set by assertions and the like.
 */
MozCrashReason("MozCrashReason", "ping"),
/** A comma-separated string that specifies the active Nimbus experiments and rollouts, as well as their branches.
 */
NimbusEnrollments("NimbusEnrollments", "ping"),
/** Miscellaneous notes that can be appended to a crash.
 */
Notes("Notes", "report"),
/** Size of the allocation that caused an out-of-memory condition.
 */
OOMAllocationSize("OOMAllocationSize", "ping"),
/** The allocation's allocation stack trace, if the crash involved a bad access of a special PHC allocation. Encoded as a comma-separated list of decimal addresses.
 */
PHCAllocStack("PHCAllocStack", "report"),
/** The allocation's base address, if the crash involved a bad access of a special PHC allocation. Encoded as a decimal address.
 */
PHCBaseAddress("PHCBaseAddress", "report"),
/** The allocation's free stack trace, if the crash involved a bad access of a special PHC allocation. Encoded as a comma-separated list of decimal addresses.
 */
PHCFreeStack("PHCFreeStack", "report"),
/** The allocation kind, if the crash involved a bad access of a special PHC allocation.
 */
PHCKind("PHCKind", "report"),
/** The allocation's usable size, if the crash involved a bad access of a special PHC allocation.
 */
PHCUsableSize("PHCUsableSize", "report"),
/** Plugin filename, only the process holding the plugin has this annotation.
 */
PluginFilename("PluginFilename", "report"),
/** Display name of a plugin, only the process holding the plugin has this annotation.
 */
PluginName("PluginName", "report"),
/** Version of a plugin, only the process holding the plugin has this annotation.
 */
PluginVersion("PluginVersion", "report"),
/** Type of the process that crashed, the possible values are defined in GeckoProcessTypes.h.
 */
ProcessType("ProcessType", "report"),
/** Application UUID (e.g. ec8030f7-c20a-464f-9b0e-13a3a9e97384).
 */
ProductID("ProductID", "ping"),
/** Application name (e.g. Firefox).
 */
ProductName("ProductName", "ping"),
/** The directory of the active profile, if any.
 */
ProfileDirectory("ProfileDirectory", "client"),
/** When a child process shuts down, this describes if the profiler is running, and the point the profiler shutdown sequence has reached.
 */
ProfilerChildShutdownPhase("ProfilerChildShutdownPhase", "ping"),
/** macOS only. Amount of physical memory currently allocated but which may be deallocated by the system in case of memory pressure. Populated from vm_statistics64_data_t::purgeable_count * vm_page_size.
 */
PurgeablePhysicalMemory("PurgeablePhysicalMemory", "ping"),
/** This annotation is present if the quota manager shutdown (resp. the shutdown of the quota manager clients) was not finished in time and the browser was crashed instead of waiting for the shutdown to finish. The status of objects which were blocking completion of the shutdown when reaching the timeout is contained in the annotation.
In the case of IndexedDB, objects are divided into three groups: FactoryOperations, LiveDatabases and DatabaseMaintenances.
In the case of LocalStorage, objects are divided into three groups: PrepareDatastoreOperations, Datastores and LiveDatabases.
In the case of Cache API, objects are in one group only: Managers.
Each group is reported separately and contains the number of objects in the group and the status of individual objects in the group (duplicate entries are removed): "GroupName: N (objectStatus1, objectStatus2, ...)" where N is the number of objects in the group.
The status of individual objects is constructed by taking selected object properties. Properties which contain origin strings are anonymized.
In addition, intermediate steps are recorded for change events after shutdown started. These include the time difference and the type of object.
 */
QuotaManagerShutdownTimeout("QuotaManagerShutdownTimeout", "ping"),
/** On Windows, this indicates if QM's base dir lives on a network resource. It is the direct result of the Win32 API function PathIsNetworkPath.
 */
QuotaManagerStorageIsNetworkResource("QuotaManagerStorageIsNetworkResource", "report"),
/** Status of the RDD process, can be set to "Running" or "Destroyed"
 */
RDDProcessStatus("RDDProcessStatus", "report"),
/** Application release channel (e.g. default, beta, ...)
 */
ReleaseChannel("ReleaseChannel", "ping"),
/** Set to 1 when the Remote Agent (WebDriver BiDi) is enabled.
 */
RemoteAgent("RemoteAgent", "report"),
/** Type of the content process, can be set to "web", "file" or "extension".
 */
RemoteType("RemoteType", "ping"),
/** Set to 1 if the browser was started in safe mode.
 */
SafeMode("SafeMode", "report"),
/** Time in seconds since the last crash occurred.
 */
SecondsSinceLastCrash("SecondsSinceLastCrash", "ping"),
/** URL used to post the crash report.
 */
ServerURL("ServerURL", "client"),
/** Shutdown step at which the browser crashed, can be set to "quit-application", "profile-change-teardown", "profile-before-change", "xpcom-will-shutdown" or "xpcom-shutdown".
 */
ShutdownProgress("ShutdownProgress", "ping"),
/** One out of "Unknown", "AppClose", "AppRestart", "OSForceClose", "OSSessionEnd" or "OSShutdown".
 */
ShutdownReason("ShutdownReason", "ping"),
/** Stack traces extracted from the crash minidump, if available. These are sent in pings, however they are extracted and transformed into a different format. The field in the extra file is meant only for client use.
 */
StackTraces("StackTraces", "client"),
/** True if the startup cache was deemed valid and usable. Will be false if the last session used a different browser version or had a startup cache.
 */
StartupCacheValid("StartupCacheValid", "report"),
/** If set to 1 then this crash occurred during startup.
 */
StartupCrash("StartupCrash", "ping"),
/** The time when Firefox was launched expressed in seconds since the Epoch.
 */
StartupTime("StartupTime", "report"),
/** This annotation is added when a mozStorage connection has not been properly closed during shutdown. The annotation holds the filename of the database associated with the connection.
 */
StorageConnectionNotClosed("StorageConnectionNotClosed", "report"),
/** This annotation can hold one of the following five values depending on how this crash was submitted by the user: * Auto: the user had opted-in to auto-submission * Infobar: the user clicked on the infobar to submit the crash * AboutCrashes: the user sent the crash from the about:crashes page * CrashedTab: the user sent the crash from a crashed tab page * Client: the user sent the crash using the crash reporter client
 */
SubmittedFrom("SubmittedFrom", "report"),
/** Windows-only, percentage of physical memory in use. This annotation is populated with the contents of the MEMORYSTATUSEX's structure dwMemoryLoad field.
 */
SystemMemoryUsePercentage("SystemMemoryUsePercentage", "ping"),
/** Telemetry client ID.
 */
TelemetryClientId("TelemetryClientId", "client"),
/** The telemetry environment in JSON format.
 */
TelemetryEnvironment("TelemetryEnvironment", "report"),
/** Telemetry profile group ID.
 */
TelemetryProfileGroupId("TelemetryProfileGroupId", "client"),
/** Telemetry server URL. Used to send main process crash pings directly from the crashreporter client.
 */
TelemetryServerURL("TelemetryServerURL", "client"),
/** Telemetry session ID.
 */
TelemetrySessionId("TelemetrySessionId", "client"),
/** Annotation used in tests.
 */
TestBoolean("TestBoolean", "report"),
/** Annotation used in tests.
 */
TestInteger("TestInteger", "report"),
/** Annotation used in tests.
 */
TestKey("TestKey", "report"),
/** Annotation used in tests.
 */
TestUnicode("TestUnicode", "report"),
/** Amount of memory in bytes consumed by textures.
 */
TextureUsage("TextureUsage", "ping"),
/** Whether Socorro can selectively discard this crash report or not. If set to "0" the crash report will always be processed by Socorro. Do not set this annotation within Gecko code, it's only supposed to be used by the crash reporting machinery.
 */
Throttleable("Throttleable", "report"),
/** Maximum amount of memory that can be committed without extending the swap/page file. - Under Windows, populated with the contents of the PERFORMANCE_INFORMATION's
  structure CommitLimit field.
- Under Linux, populated with /proc/meminfo MemTotal + SwapTotal. The swap file
  typically cannot be extended, so that's a hard limit.
- Not available on other systems.
 */
TotalPageFile("TotalPageFile", "ping"),
/** Amount of physical memory in bytes. - Under Windows, populated with the contents of the MEMORYSTATUSEX's structure ullTotalPhys field. - Under macOS, populated with sysctl "hw.memsize". - Under Linux, populated with /proc/meminfo's "MemTotal". - Not available on other systems.
 */
TotalPhysicalMemory("TotalPhysicalMemory", "ping"),
/** Size of the virtual address space. - Under Windows, populated with the contents of the MEMORYSTATUSEX's structure
  ullTotalVirtual field.
- Not available on other platforms.
 */
TotalVirtualMemory("TotalVirtualMemory", "ping"),
/** An unknown network address family was requested to Necko. The value is the requested family number.
 */
UnknownNetAddrSocketFamily("UnknownNetAddrSocketFamily", "report"),
/** Uptime in seconds. This annotation uses a string instead of an integer because it has a fractional component.
 */
UptimeTS("UptimeTS", "ping"),
/** URL being loaded.
 */
URL("URL", "report"),
/** The offsets of the nsStandardURL segments that fail a sanity check
 */
URLSegments("URLSegments", "report"),
/** Set to 1 if user32.dll was loaded before we could install the DLL blocklist.
 */
User32BeforeBlocklist("User32BeforeBlocklist", "ping"),
/** User-agent locale.
 */
useragent_locale("useragent_locale", "report"),
/** Comma-separated list of IPC actors name running on this Utility process instance
 */
UtilityActorsName("UtilityActorsName", "ping"),
/** Status of the Utility process, can be set to "Running" or "Destroyed"
 */
UtilityProcessStatus("UtilityProcessStatus", "report"),
/** Application vendor (e.g. Mozilla).
 */
Vendor("Vendor", "report"),
/** Product version.
 */
Version("Version", "ping"),
/** Status of the VR process, can be set to "Running" or "Destroyed"
 */
VRProcessStatus("VRProcessStatus", "report"),
/** Set to 1 if a rlbox wasm library sandbox ran out of memory, causing a malloc inside the sandbox to fail.
 */
WasmLibrarySandboxMallocFailed("WasmLibrarySandboxMallocFailed", "report"),
/** Set to 1 if this crash was intercepted via the Windows Error Reporting runtime exception module.
 */
WindowsErrorReporting("WindowsErrorReporting", "ping"),
/** The HRESULT returned from a Win32 system call leading to termination of the file-dialog utility process. MozCrashReason is expected to provide context for the value.
 */
WindowsFileDialogErrorCode("WindowsFileDialogErrorCode", "ping"),
/** If running in a Windows package context, the package family name, per https://docs.microsoft.com/en-us/windows/win32/api/appmodel/nf-appmodel-getcurrentpackagefamilyname.
The package family name is only included when it is likely to have been produced by Mozilla: it starts "Mozilla." or "MozillaCorporation.".
 */
WindowsPackageFamilyName("WindowsPackageFamilyName", "ping"),
/** Information on winsock LSPs injected in our networking stack.
 */
Winsock_LSP("Winsock_LSP", "report"),
/** If we crash while some code is spinning manually the event loop on the main thread, we will see the stack of nested annotations here. If the crashing process was killed (e.g. due to an IPC error), this annotation may refer to the parent process that killed it, look out for the prefix ("default" means parent) and see bug 1741131 for details.
 */
XPCOMSpinEventLoopStack("XPCOMSpinEventLoopStack", "report");

        private final String s;
        private final String scope;

        private Annotation(String s, String scope) {
            this.s = s;
            this.scope = scope;
        }

        public String toString() {
            return this.s;
        }

        /** @return Whether the annotation should be included in crash pings. */
        public boolean allowedInPing() {
            return this.scope.equals("ping");
        }

        /** @return Whether the annotation should be included in crash reports. */
        public boolean allowedInReport() {
            return allowedInPing() || this.scope.equals("report");
        }
    }
}
